apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mp4-efs-pvc
  namespace: maifocus-ns-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi  # optional for EFS

