apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  name: nginx-rtmp-service
  namespace: maifocus-ns-prod
spec:
  selector:
    app: nginx
  ports:
  - port: 1935
    targetPort: 1935
  type: LoadBalancer

